# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
    
pr: none

pool:
    vmImage: 'vs2017-win2016'

steps:
    - checkout: self

    - task: NodeTool@0
      displayName: 'Use Node 10.x'
      inputs:
          versionSpec: 10.x
          checkLatest: true

    - task: Npm@1
      displayName: 'npm install'
      inputs:
        command: 'install'
        workingDir: 'CustomWebparts'
        verbose: false   

    - task: Gulp@1
      displayName: 'Gulp Build'
      inputs:
          gulpFile: 'CustomWebparts/gulpfile.js'
          workingDirectory: 'CustomWebparts'
          targets: build 
          
    - task: Gulp@1
      inputs:
        gulpFile: 'CustomWebparts/gulpfile.js'
        workingDirectory: 'CustomWebparts'
        targets: 'bundle'
        gulpjs: 'node_modules/gulp/bin/gulp.js'
        enableCodeCoverage: false
        arguments: '--ship'
        
    - task: Gulp@0
      displayName: 'gulp package-solution'
      inputs:
        gulpFile: 'CustomWebparts/gulpfile.js'
        workingDirectory: 'CustomWebparts'
        targets: 'package-solution'
        arguments: '--ship'
    
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(build.artifactstagingdirectory)/drop'
      inputs:
          Contents: '**\*.sppkg'
          TargetFolder: '$(build.artifactstagingdirectory)/drop'


    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
