define([], function() {
  return {
    "PropertyPaneDescription": "Handbook Listing Web Part",
    "BasicGroupName": "Properties",
    "DescriptionFieldLabel": "Description Field",
    "contentTypelabel": "Page Content Type",
    "errorLoggingGroupName": "Error logging properties",
    "siteURLforLogsLabel": "Site URL for Error Logging",
    "errorLogApptitleLabel": "Application Title for Error Log",
    "writeDebugLogsLabel": "Write Debug Logs",
    "typeOfPagesToShowLabel": "Select Type of Pages to Show",
    "typeOfPagesShowOptionKey": "ShowAll",
    "typeOfPagesShowOptionText": "Show All",
    "typeOfPagesListingOptionKey": "IncludedInListing",
    "typeOfPagesListingOptionText": "Show only Included in Listing",
    "showChildOrGrandChildLabel": "Show Child or Child and GrandChild",
    "childOptionKey": "ShowonlyChild",
    "childOptionText": "Show only Child",
    "childGrandChildOptionKey": "ShowChildAndGrandChild",
    "childGrandChildOptionText": "Show Child And GrandChild",
    "createColInternalName": "Created",
    "pageNameColInternalName": "Name",
    "additionFieldLabel": "Select Additional Field To Display",
    "emptyString": "",
    "colTypeDateTime": "DateTime",
    "colTypeText": "Text",
    "colTypeUserMulti": "UserMulti",
    "colTypeTaxonomyFieldTypeMulti": "TaxonomyFieldTypeMulti",
    "colTypeTaxonomyFieldType": "TaxonomyFieldType",
    "principalNameIntials": "i:0#.f|membership|",
    "colTypeLookup": "Lookup",
    "monthNames": ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
    "sortByColumnNameLabel": "Select Field to Sort",
    "warningMessageofAdditionalFieldSelection": "Only 4 columns can be selected at once !! ",
    "sortByDefaultColKey": "Title",
    "sortByDefaultColText": "Title",
    "sortByAscOrDescLabel": "Select the Sort Order",
    "ascendingOptionKey": "Asc",
    "ascendingOptionText": "Ascending",
    "descendingOptionKey": "Desc",
    "descendingOptionText": "Descending",
    "defaultShowChildCount": 3,
    "alphaNumericSorting": "en-u-kn-true",
    "childNodesPropertyName": "childNodes",
    "purposeSorting": "Sort",
    "purposeDisplaying": "Display",
    "maxCountInAddCol" : 4,
    "defaultShowChildCountLabel" : "Number of Child to Display",
    "defaultShowChildCountDesc" : "Provide default Number of child to display when page loaded then Show More link will be there",
    "dynamicPropertyId": "event",
    "dynamicPropertyTitle": "Child Listing Data",
    "siblingListingOptionKey": "Sibling",
    "siblingListingOptionText": "Sibling",
    "childListingOptionKey": "Child",
    "childListingOptionText": "Child",
    "webPartViewLabel": "Web Part View",
    "callOutIconType":"Info",
    "callOutRole": "alertdialog",
  }
});