declare interface IEhsHandbookListingWebPartStrings {
  PropertyPaneDescription: string;
  BasicGroupName: string;
  DescriptionFieldLabel: string;
  contentTypelabel: string;
  errorLoggingGroupName: string;
  siteURLforLogsLabel: string;
  errorLogApptitleLabel: string;
  writeDebugLogsLabel: string;
  typeOfPagesToShowLabel: string;
  typeOfPagesShowOptionKey: string;
  typeOfPagesShowOptionText: string;
  typeOfPagesListingOptionKey: string;
  typeOfPagesListingOptionText: string;
  showChildOrGrandChildLabel: string;
  childOptionKey: string;
  childOptionText: string;
  childGrandChildOptionKey: string;
  childGrandChildOptionText: string;
  createColInternalName: string;
  pageNameColInternalName: string;
  additionFieldLabel: string;
  emptyString: string;
  colTypeDateTime: string;
  colTypeText: string;
  colTypeUserMulti: string;
  colTypeTaxonomyFieldTypeMulti: string;
  colTypeTaxonomyFieldType: string;
  colTypeLookup: string;
  principalNameIntials: string;
  monthNames: string[];
  sortByColumnNameLabel: string;
  warningMessageofAdditionalFieldSelection: string;
  sortByDefaultColKey: string;
  sortByDefaultColText: string;
  sortByAscOrDescLabel : string;
  ascendingOptionKey : string;
  ascendingOptionText : string;
  descendingOptionKey : string;
  descendingOptionText : string;
  childNodesNodeName : string;
  defaultShowChildCount : number;
  alphaNumericSorting : string;
  childNodesPropertyName : string;
  purposeSorting : string;
  purposeDisplaying : string;
  maxCountInAddCol : number;
  defaultShowChildCountLabel : string;
  defaultShowChildCountDesc : string;
  dynamicPropertyId: string;
  dynamicPropertyTitle: string;
  siblingListingOptionKey: string;
  siblingListingOptionText: string;
  childListingOptionKey: string;
  childListingOptionText: string;
  webPartViewLabel: string;
  callOutIconType: string;
  callOutRole: string;
}

declare module 'EhsHandbookListingWebPartStrings' {
  const strings: IEhsHandbookListingWebPartStrings;
  export = strings;
}
